### ISSUE TITLE
Default to not fetching DTDs from the network

### ISSUE THREAD

**Issue by trejkaz** [xmlunit/xmlunit#91] opened 2016-12-13 23:57 UTC
I found us having to workaround this one:

        // This is to disable DTD lookups on the internet
        DocumentBuilderFactory dbf = XMLUnit.getControlDocumentBuilderFactory();
        dbf.setFeature("http://xml.org/sax/features/validation", false);
        dbf.setFeature("http://apache.org/xml/features/nonvalidating/load-dtd-grammar", false);
        dbf.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);

I think that by default, at least loading external DTDs should be disabled, since I prefer to have my tests reliably pass without external factors being able to trigger failures. (I don't particularly mind validation being left turned on for DTDs which are local... and am not entirely sure why we are disabling that as well.)

**Comment by bodewig** [comment] 2016-12-14 03:11
Hmm, I'm not convinced this should be the default, but we could certainly make things easier for people by providing a configuration option for this so people don't need to figure out the features. The `apache` features you list only apply to Xerces (and probably the Xerces included within Oracle's JDKs), right?

Your code looks as if you'd still be using XMLUnit 1.x. Is this 2.x's legacy jar or "the real 1.x"?

**Comment by trejkaz** [comment] 2016-12-14 05:13
Looks like it's actual 1.x.

{code}
 xmlunit: [ 'xmlunit:xmlunit:1.6' ],
{code}

Should we bump to 2 and see what breaks? :D

**Comment by bodewig** [comment] 2016-12-14 15:42
2.x is deliberately very different to 1.x but the legacy project should be a drop-in replacement. I'm not really sure I want to cut a new 1.x release at all anymore. If the legacy jar works for you, that would be fine.

It should be pretty easy to have all DTDs available locally if you configure an entity resolver (using an XML catalog or whatever) but I don't really see what XMLUnit could do to help apart from making i easier to specify an entity resolver.

The topic hasn't really come up before, I guess most people aren't using DTDs at all or use DTDs with only local SYSTEM ids (or none at all).

I get your point about reproducibility but OTOH don't want to silently configure features of the XML parser most people have probably never heard about. IMHO things should be made explicit.

**Comment by trejkaz** [comment] 2017-11-13 03:18
In updating to the matchers style, I'm half way towards this not really mattering.

For equality checks I can just set up a document builder factory and override it:

```
assertThat(actual, isIdenticalTo(expected)
    .withDocumentBuilderFactory(documentBuilderFactory));
```

For `hasXPath` I'd like to do something similar, but it doesn't seem to have an equivalent at all right now.

I guess I can wrap the matcher and do the parsing myself though, and delegate the call with the node...

**Comment by bodewig** [comment] 2017-11-13 05:50
I intend to tackle this with 2.6.0 by providing some simplified setup of a `DocumentBuilderFactory` but wo't find time to do so the coming days.

The XPath related matchers use `Convert.toNode` without specifying a factory. It should be easy to add a setter for a factory much like the one of `CompareMatcher` and use that if it has been specified. I'll open a new issue for that.

**Comment by bodewig** [comment] 2018-01-07 18:37
#108 is now fixed in the master branch. I still plan fixing this issue and cutting a 2.6.0 release soon.

**Comment by bodewig** [comment] 2018-04-13 21:15
I've started adding disabling DTD loading in the branch https://github.com/xmlunit/xmlunit/tree/add-some-xxe-protection and strangely all unit tests still pass, so I wonder whether I've done something wrong. If you could spare a moment to look at my change @trejkaz I'd be grateful.

**Comment by bodewig** [comment] 2018-04-13 21:32
Ah, I think this is because the only tests that rely on DTD processing use the validation package which uses `SAXParser` rather than `DocumentBuilderFactory`, which I haven't covered, yet.

It feels wrong to disable DTD processing in a class dedicated to validating XML documents against a DTD, so I won't touch this, I guess. I'll just make the `validate` method public which allows the `SaxParserFactory` to be passed in.

**Closed** 2018-04-14 14:00 UTC
Labels: core, enhancement, java-legacy

**Comment by bodewig** [comment] 2018-04-14 14:04
I think I've covered most places - and despite this issues title the legacy package has the XXE protection disabled. Feedback before I cut the 2.6.0 release would be greatly appreciated.

**Comment by trejkaz** [comment] 2018-04-16 01:16
I gave the snapshot a spin on our project here, and it works for us. (I stepped in to check that the DTD parsing was really off, but also ran on all tests to see if any new failures would appear.)

**Comment by bodewig** [comment] 2018-04-16 03:52
great, thanks

**Comment by janssen** [comment] 2018-07-03 01:00
So, for those of us non-experts, how exactly in 2.6 do you compare two XML docs without validating?  The W3C seems to have disabled internet XHTML validation by removing http://www.w3.org/TR/xhtml11/DTD/xhtml-datatypes-1.mod, so I'm suddenly in dire need of being able to not validate.

Should we still use the code at the top of this issue?

**Comment by trejkaz** [comment] 2018-07-03 05:02
I double-checked the actual 2.6.0 release and the default `DocumentBuilderFactory` set in the builder now turns off almost all the features we were turning off.

So now you can get away with just asserts like:

    assertThat(xml, hasXPath("//D:response"));

If you were paranoid you could chain on a call to `withDocumentBuilderFactory` to set your own factory anyway.

(On the other hand, I went to check up on our XHTML validation, and I guess that's still working, because we must be loading those DTDs from the local filesystem already.)
